In [215]:
import pandas as pd

In [216]:
# Try loading the CSV again with the 'python' engine, which is more robust for malformed files
df = pd.read_csv(r"C:\Users\Ayobami Adeyemo\Downloads\results (2).txt", encoding='utf-8-sig', on_bad_lines='skip', engine='python')

# Display the first 50 rows
display(df.head(5))

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,...,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
1,2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,All skills. AI is a flop.,104413.0,9.0
2,3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I want to...,"Understand how things actually work, problem s...",53061.0,8.0
3,4,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code,NaN,When I don’t trust AI’s answers;When I want to...,NaN,36197.0,6.0
4,5,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc.)",21.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers,"critical thinking, the skill to define the tas...",60000.0,7.0

In [217]:
df.shape

(49190, 172)

In [218]:
df.iloc[:, :20].head(2)

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,YearsCode,DevType,OrgSize,ICorPM,RemoteWork,PurchaseInfluence,TechEndorseIntro,TechEndorse_1,TechEndorse_2
0,1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,14.0,"Developer, mobile",20 to 99 employees,People manager,Remote,"Yes, I influenced the purchase of a substantia...",Work,10.0,7.0
1,2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,10.0,"Developer, back-end",500 to 999 employees,Individual contributor,"Hybrid (some in-person, leans heavy to flexibi...",No,Personal Project,13.0,1.0

In [219]:
df.iloc[:, 20:40].head(2)

,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,TechEndorse_9,TechEndorse_13,TechEndorse_13_TEXT,TechOppose_1,TechOppose_2,TechOppose_3,TechOppose_5,TechOppose_7,TechOppose_9,TechOppose_11,TechOppose_13,TechOppose_16,TechOppose_15,TechOppose_15_TEXT
0,9.0,6.0,3.0,11.0,12.0,1.0,8.0,14.0,NaN,15.0,7.0,8.0,12.0,11.0,1.0,6.0,13.0,3.0,16.0,NaN
1,2.0,9.0,4.0,3.0,12.0,5.0,7.0,14.0,NaN,14.0,1.0,13.0,10.0,9.0,3.0,4.0,2.0,5.0,15.0,NaN

### Use SQL to drop anything that starts with *Tech

In [220]:
df.iloc[:, 40:60].head(2)

,Industry,JobSatPoints_1,JobSatPoints_2,JobSatPoints_3,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,JobSatPoints_13,JobSatPoints_14,JobSatPoints_15,JobSatPoints_16,JobSatPoints_15_TEXT,AIThreat,NewRole,ToolCountWork
0,Fintech,3.0,1.0,4.0,9.0,5.0,10.0,12.0,11.0,2.0,6.0,7.0,13.0,14.0,15.0,8.0,NaN,I'm not sure,I have neither consider or transitioned into a...,7.0
1,Retail and Consumer Services,10.0,8.0,3.0,9.0,12.0,1.0,6.0,2.0,11.0,4.0,7.0,13.0,14.0,15.0,5.0,NaN,I'm not sure,I have transitioned into a new career and/or i...,6.0

### Use SQL to drop anything that starts with *Job

In [221]:
df.iloc[:, 60:80].head(2)

,ToolCountPersonal,Country,Currency,CompTotal,LanguageChoice,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,LanguagesHaveEntry,LanguagesWantEntry,DatabaseChoice,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,DatabaseHaveEntry,DatabaseWantEntry,PlatformChoice,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired
0,3.0,Ukraine,EUR European Euro,52800.0,Yes,Bash/Shell (all shells);Dart;SQL,Dart,Dart,NaN,NaN,Yes,Cloud Firestore;PostgreSQL,NaN,NaN,NaN,NaN,Yes,Amazon Web Services (AWS);Cloudflare;Firebase;...,NaN,NaN
1,5.0,Netherlands,EUR European Euro,90000.0,Yes,Java,Java;Python;Swift,Java,NaN,NaN,Yes,Dynamodb;MongoDB,Dynamodb;MongoDB,Dynamodb;MongoDB,NaN,NaN,Yes,Amazon Web Services (AWS);Datadog;Docker;Homeb...,Amazon Web Services (AWS);Datadog;Docker;Homeb...,Amazon Web Services (AWS);Datadog;Docker;Homeb...

In [222]:
df.iloc[:, 80:100].head(2)

,PlatformHaveEntry,PlatformWantEntry,WebframeChoice,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,WebframeHaveEntry,WebframeWantEntry,DevEnvsChoice,DevEnvsHaveWorkedWith,DevEnvsWantToWorkWith,DevEnvsAdmired,DevEnvHaveEntry,DevEnvWantEntry,SOTagsHaveWorkedWith,SOTagsWantToWorkWith,SOTagsAdmired,SOTagsHaveEntry,SOTagsWant Entry,OpSysPersonal use
0,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,Android Studio;Notepad++;Visual Studio;Visual ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows;MacOS;Android
1,NaN,NaN,Yes,Spring Boot,Spring Boot,Spring Boot,NaN,NaN,Yes,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows;MacOS;iOS;iPadOS

In [223]:
df.iloc[:, 100:120].head(2)

,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackHaveEntry,OfficeStackWantEntry,CommPlatformHaveWorkedWith,CommPlatformWantToWorkWith,CommPlatformAdmired,CommPlatformHaveEntr,CommPlatformWantEntr,AIModelsChoice,AIModelsHaveWorkedWith,AIModelsWantToWorkWith,AIModelsAdmired,AIModelsHaveEntry,AIModelsWantEntry,SOAccount,SOVisitFreq,SODuration
0,Windows;MacOS;Android;iOS;iPadOS,Confluence;GitHub;GitLab;Jira;Markdown File,Markdown File,Markdown File,NaN,NaN,"Stack Overflow;Reddit;GitHub (public projects,...",NaN,NaN,NaN,NaN,Yes,openAI GPT (chatbot models);openAI Image gener...,NaN,NaN,NaN,NaN,Yes,A few times per week,Between 5 and 10 years
1,MacOS,Confluence;GitHub;Jira,Confluence;GitHub;Jira,Confluence;GitHub;Jira,NaN,NaN,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,NaN,NaN,Yes,openAI GPT (chatbot models),openAI GPT (chatbot models),openAI GPT (chatbot models),NaN,NaN,Not sure/can't remember,Multiple times per day,Between 10 and 15 years

In [224]:
df.iloc[:, 120:140].head(10)

,SOPartFreq,SO_Dev_Content,SO_Actions_1,SO_Actions_16,SO_Actions_3,SO_Actions_4,SO_Actions_5,SO_Actions_6,SO_Actions_9,SO_Actions_7,SO_Actions_10,SO_Actions_15,SO_Actions_15_TEXT,SOComm,SOFriction,AISelect,AISent,AIAcc,AIComplex,AIToolCurrently partially AI
0,I have never participated in Q&A on Stack Over...,NaN,1.0,NaN,6.0,2.0,3.0,7.0,8.0,9.0,11.0,15.0,NaN,Neutral,"Rarely, almost never","Yes, I use AI tools monthly or infrequently",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,Learning about a codebase;Writing code;Search ...
1,"Infrequently, less than once per year",Chat (people);Message Boards;Long-form article...,6.0,NaN,5.0,8.0,2.0,4.0,9.0,10.0,11.0,15.0,NaN,"Yes, somewhat",About half of the time,"Yes, I use AI tools weekly",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,Learning new concepts or technologies
2,"Infrequently, less than once per year",Chat (people);Videos;Lists of recommendations ...,3.0,NaN,4.0,5.0,1.0,2.0,7.0,9.0,11.0,15.0,NaN,Neutral,About half of the time,"Yes, I use AI tools daily",Favorable,Somewhat trust,Neither good or bad at handling complex tasks,Documenting code;Debugging or fixing code;Test...
3,I have never participated in Q&A on Stack Over...,Videos;Chat (bot/AI),1.0,NaN,4.0,5.0,6.0,7.0,8.0,9.0,11.0,15.0,NaN,Neutral,"Rarely, almost never","Yes, I use AI tools weekly",Favorable,Somewhat trust,Bad at handling complex tasks,NaN
4,"Infrequently, less than once per year",Long-form articles,1.0,NaN,7.0,4.0,2.0,5.0,10.0,6.0,12.0,15.0,NaN,"No, not really","Rarely, almost never","Yes, I use AI tools weekly",Favorable,Neither trust nor distrust,"Good, but not great at handling complex tasks",Learning about a codebase;Writing code;Debuggi...
5,"Infrequently, less than once per year","Lists of recommendations (tools, frameworks, t...",6.0,NaN,9.0,3.0,4.0,5.0,10.0,1.0,11.0,15.0,NaN,"Yes, somewhat","Rarely, almost never","Yes, I use AI tools daily",Indifferent,Somewhat distrust,"Good, but not great at handling complex tasks",Learning about a codebase;Writing code;Documen...
6,"Infrequently, less than once per year",Long-form articles;Videos;Lists of recommendat...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Yes, I use AI tools daily",Favorable,Somewhat trust,Neither good or bad at handling complex tasks,Learning about a codebase;Writing code;Documen...
7,"Infrequently, less than once per year",Chat (people);Message Boards;Long-form article...,7.0,NaN,10.0,1.0,6.0,5.0,4.0,2.0,11.0,15.0,NaN,"Yes, definitely",About half of the time,"Yes, I use AI tools daily",Very favorable,Somewhat trust,Neither good or bad at handling complex tasks,Writing code;Documenting code
8,NaN,NaN,1.0,NaN,4.0,5.0,6.0,7.0,8.0,9.0,11.0,15.0,NaN,NaN,NaN,"Yes, I use AI tools monthly or infrequently",Indifferent,Neither trust nor distrust,Neither good or bad at handling complex tasks,NaN
9,I have never participated in Q&A on Stack Over...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"No, not really",I don't use AI or AI-enabled tools,"No, and I don't plan to",Unfavorable,Highly distrust,Very poor at handling complex tasks,NaN

In [225]:
df.iloc[:, 140:160].head(2)

,AIToolDon't plan to use AI for this task,AIToolPlan to partially use AI,AIToolPlan to mostly use AI,AIToolCurrently mostly AI,AIFrustration,AIExplain,AIAgents,AIAgentChange,AIAgent_Uses,AgentUsesGeneral,AIAgentImpactSomewhat agree,AIAgentImpactNeutral,AIAgentImpactSomewhat disagree,AIAgentImpactStrongly agree,AIAgentImpactStrongly disagree,AIAgentChallengesNeutral,AIAgentChallengesSomewhat disagree,AIAgentChallengesStrongly agree,AIAgentChallengesSomewhat agree,AIAgentChallengesStrongly disagree
0,Project planning;Deployment and monitoring;Lea...,Documenting code;Debugging or fixing code;Test...,NaN,NaN,"AI solutions that are almost right, but not quite",No,"Yes, I use AI agents at work monthly or infreq...",Not at all or minimally,Software engineering,NaN,AI agents have increased my productivity.;AI a...,AI agents have helped me automate repetitive t...,NaN,NaN,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,The cost of using certain AI agent platforms i...,NaN,NaN
1,Learning about a codebase;Project planning;Com...,Writing code;Documenting code;Debugging or fix...,NaN,NaN,"AI solutions that are almost right, but not qu...",No,"No, and I don't plan to",Not at all or minimally,NaN,NaN,NaN,NaN,NaN,NaN,NaN,It takes significant time and effort to learn ...,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,NaN

In [226]:
df.iloc[:, 160:180].head(2)

,AIAgentKnowledge,AIAgentKnowWrite,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
0,NaN,NaN,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,All skills. AI is a flop.,104413.0,9.0

In [227]:
import sqlite3
import pandas as pd

conn = sqlite3.connect(":memory:")
df.to_sql("new_file", conn, index=False)

columns = [
    "ResponseId", "Age", "EdLevel", "Employment", "WorkExp", "YearsCode",
    "DevType", "OrgSize", "ICorPM", "RemoteWork", "Industry", "AIThreat",
    "NewRole", "ToolCountWork", "ToolCountPersonal", "Country", "Currency",
    "CompTotal", "AISelect", "AIAgents", "ConvertedCompYearly", "JobSat"
]

# Keep only columns that actually exist in df
existing = [c for c in columns if c in df.columns]

query = f"SELECT {', '.join(existing)} FROM new_file"
result = pd.read_sql_query(query, conn)

display(result.head(10))

,ResponseId,Age,EdLevel,Employment,WorkExp,YearsCode,DevType,OrgSize,ICorPM,RemoteWork,...,NewRole,ToolCountWork,ToolCountPersonal,Country,Currency,CompTotal,AISelect,AIAgents,ConvertedCompYearly,JobSat
0,1,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,8.0,14.0,"Developer, mobile",20 to 99 employees,People manager,Remote,...,I have neither consider or transitioned into a...,7.0,3.0,Ukraine,EUR European Euro,52800.0,"Yes, I use AI tools monthly or infrequently","Yes, I use AI agents at work monthly or infreq...",61256.0,10.0
1,2,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,2.0,10.0,"Developer, back-end",500 to 999 employees,Individual contributor,"Hybrid (some in-person, leans heavy to flexibi...",...,I have transitioned into a new career and/or i...,6.0,5.0,Netherlands,EUR European Euro,90000.0,"Yes, I use AI tools weekly","No, and I don't plan to",104413.0,9.0
2,3,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",10.0,12.0,"Developer, front-end",NaN,NaN,NaN,...,I have transitioned into a new career and/or i...,3.0,3.0,Ukraine,UAH Ukrainian hryvnia,2214000.0,"Yes, I use AI tools daily","Yes, I use AI agents at work weekly",53061.0,8.0
3,4,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,4.0,5.0,"Developer, back-end","10,000 or more employees",Individual contributor,Remote,...,I have neither consider or transitioned into a...,NaN,NaN,Ukraine,EUR European Euro,31200.0,"Yes, I use AI tools weekly","Yes, I use AI agents at work monthly or infreq...",36197.0,6.0
4,5,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...",21.0,22.0,Engineering manager,NaN,NaN,NaN,...,I have neither consider or transitioned into a...,4.0,3.0,Ukraine,USD United States dollar,60000.0,"Yes, I use AI tools weekly","No, and I don't plan to",60000.0,7.0
5,6,45-54 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...",15.0,20.0,"Developer, back-end",NaN,NaN,NaN,...,I have somewhat considered changing my career ...,5.0,5.0,Ukraine,USD United States dollar,120000.0,"Yes, I use AI tools daily","Yes, I use AI agents at work monthly or infreq...",120000.0,7.0
6,7,25-34 years old,Some college/university study without earning ...,"Independent contractor, freelancer, or self-em...",9.0,13.0,"Developer, full-stack",NaN,NaN,NaN,...,I have somewhat considered changing my career ...,NaN,NaN,Ukraine,USD United States dollar,6240.0,"Yes, I use AI tools daily","Yes, I use AI agents at work monthly or infreq...",6240.0,6.0
7,8,35-44 years old,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)",Employed,22.0,30.0,"Architect, software or solutions",Less than 20 employees,People manager,Remote,...,I have strongly considered changing my career ...,10.0,10.0,Ukraine,USD United States dollar,72000.0,"Yes, I use AI tools daily","No, but I plan to",72000.0,6.0
8,9,25-34 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,9.0,15.0,Data engineer,"5,000 to 9,999 employees",Individual contributor,Remote,...,I have transitioned into a new career and/or i...,NaN,NaN,Ukraine,USD United States dollar,70000.0,"Yes, I use AI tools monthly or infrequently",NaN,70000.0,8.0
9,10,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,7.0,10.0,"Developer, mobile",20 to 99 employees,Individual contributor,Remote,...,I have somewhat considered changing my career ...,6.0,2.0,Ukraine,USD United States dollar,5400.0,"No, and I don't plan to","No, but I plan to",5400.0,4.0

In [228]:
result.shape

(49190, 22)

In [229]:
result.info()

<class 'pandas.DataFrame'>
RangeIndex: 49190 entries, 0 to 49189
Data columns (total 22 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ResponseId           49190 non-null  int64
 1   Age                  49190 non-null  str
 2   EdLevel              48148 non-null  str
 3   Employment           48338 non-null  str
 4   WorkExp              42892 non-null  float64
 5   YearsCode            43041 non-null  float64
 6   DevType              43679 non-null  str
 7   OrgSize              34178 non-null  str
 8   ICorPM               33243 non-null  str
 9   RemoteWork           33780 non-null  str
 10  Industry             33642 non-null  str
 11  AIThreat             36077 non-null  str
 12  NewRole              35526 non-null  str
 13  ToolCountWork        27610 non-null  float64
 14  ToolCountPersonal    25581 non-null  float64
 15  Country              35436 non-null  str
 16  Currency             35436 non-null  str
 17  CompTotal            24866 non-null  float64
 18  AISelect             33719 non-null  str
 19  AIAgents             31918 non-null  str
 20  ConvertedCompYearly  23947 non-null  float64
 21  JobSat               26670 non-null  float64
dtypes: float64(7), int64(1), str(14)
memory usage: 8.3 MB

In [230]:
df = result.copy()
df

,ResponseId,Age,EdLevel,Employment,WorkExp,YearsCode,DevType,OrgSize,ICorPM,RemoteWork,...,NewRole,ToolCountWork,ToolCountPersonal,Country,Currency,CompTotal,AISelect,AIAgents,ConvertedCompYearly,JobSat
0,1,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,8.0,14.0,"Developer, mobile",20 to 99 employees,People manager,Remote,...,I have neither consider or transitioned into a...,7.0,3.0,Ukraine,EUR European Euro,52800.0,"Yes, I use AI tools monthly or infrequently","Yes, I use AI agents at work monthly or infreq...",61256.0,10.0
1,2,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,2.0,10.0,"Developer, back-end",500 to 999 employees,Individual contributor,"Hybrid (some in-person, leans heavy to flexibi...",...,I have transitioned into a new career and/or i...,6.0,5.0,Netherlands,EUR European Euro,90000.0,"Yes, I use AI tools weekly","No, and I don't plan to",104413.0,9.0
2,3,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",10.0,12.0,"Developer, front-end",NaN,NaN,NaN,...,I have transitioned into a new career and/or i...,3.0,3.0,Ukraine,UAH Ukrainian hryvnia,2214000.0,"Yes, I use AI tools daily","Yes, I use AI agents at work weekly",53061.0,8.0
3,4,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,4.0,5.0,"Developer, back-end","10,000 or more employees",Individual contributor,Remote,...,I have neither consider or transitioned into a...,NaN,NaN,Ukraine,EUR European Euro,31200.0,"Yes, I use AI tools weekly","Yes, I use AI agents at work monthly or infreq...",36197.0,6.0
4,5,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...",21.0,22.0,Engineering manager,NaN,NaN,NaN,...,I have neither consider or transitioned into a...,4.0,3.0,Ukraine,USD United States dollar,60000.0,"Yes, I use AI tools weekly","No, and I don't plan to",60000.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49185,49187,18-24 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49186,49188,45-54 years old,Some college/university study without earning ...,Employed,25.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49187,49189,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,17.0,31.0,"Architect, software or solutions","10,000 or more employees",People manager,"Hybrid (some in-person, leans heavy to flexibi...",...,I have somewhat considered changing my career ...,25.0,35.0,Italy,EUR European Euro,80000.0,"Yes, I use AI tools monthly or infrequently","No, I use AI exclusively in copilot/autocomple...",NaN,9.0
49188,49190,25-34 years old,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)","Independent contractor, freelancer, or self-em...",2.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49189,49191,18-24 years old,Some college/university study without earning ...,Student,NaN,6.0,Student,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [231]:
df.groupby("Age")["ResponseId"].count().sort_values(ascending=False)

Age
25-34 years old      16519
35-44 years old      13240
18-24 years old       9210
45-54 years old       6275
55-64 years old       2626
65 years or older      942
Prefer not to say      378
Name: ResponseId, dtype: int64

In [232]:
df["Age"] = df["Age"].str.replace("years old", "").str.strip()
df["Age"] = df["Age"].str.replace("years or older", "- over").str.strip()

In [233]:
df["Age"] = df["Age"].replace("Prefer not to say", pd.NA)
df

,ResponseId,Age,EdLevel,Employment,WorkExp,YearsCode,DevType,OrgSize,ICorPM,RemoteWork,...,NewRole,ToolCountWork,ToolCountPersonal,Country,Currency,CompTotal,AISelect,AIAgents,ConvertedCompYearly,JobSat
0,1,25-34,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,8.0,14.0,"Developer, mobile",20 to 99 employees,People manager,Remote,...,I have neither consider or transitioned into a...,7.0,3.0,Ukraine,EUR European Euro,52800.0,"Yes, I use AI tools monthly or infrequently","Yes, I use AI agents at work monthly or infreq...",61256.0,10.0
1,2,25-34,"Associate degree (A.A., A.S., etc.)",Employed,2.0,10.0,"Developer, back-end",500 to 999 employees,Individual contributor,"Hybrid (some in-person, leans heavy to flexibi...",...,I have transitioned into a new career and/or i...,6.0,5.0,Netherlands,EUR European Euro,90000.0,"Yes, I use AI tools weekly","No, and I don't plan to",104413.0,9.0
2,3,35-44,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",10.0,12.0,"Developer, front-end",NaN,NaN,NaN,...,I have transitioned into a new career and/or i...,3.0,3.0,Ukraine,UAH Ukrainian hryvnia,2214000.0,"Yes, I use AI tools daily","Yes, I use AI agents at work weekly",53061.0,8.0
3,4,35-44,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,4.0,5.0,"Developer, back-end","10,000 or more employees",Individual contributor,Remote,...,I have neither consider or transitioned into a...,NaN,NaN,Ukraine,EUR European Euro,31200.0,"Yes, I use AI tools weekly","Yes, I use AI agents at work monthly or infreq...",36197.0,6.0
4,5,35-44,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...",21.0,22.0,Engineering manager,NaN,NaN,NaN,...,I have neither consider or transitioned into a...,4.0,3.0,Ukraine,USD United States dollar,60000.0,"Yes, I use AI tools weekly","No, and I don't plan to",60000.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49185,49187,18-24,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49186,49188,45-54,Some college/university study without earning ...,Employed,25.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49187,49189,35-44,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,17.0,31.0,"Architect, software or solutions","10,000 or more employees",People manager,"Hybrid (some in-person, leans heavy to flexibi...",...,I have somewhat considered changing my career ...,25.0,35.0,Italy,EUR European Euro,80000.0,"Yes, I use AI tools monthly or infrequently","No, I use AI exclusively in copilot/autocomple...",NaN,9.0
49188,49190,25-34,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)","Independent contractor, freelancer, or self-em...",2.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49189,49191,18-24,Some college/university study without earning ...,Student,NaN,6.0,Student,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [234]:
df.groupby("Age")["ResponseId"].count().sort_values(ascending=False)

Age
25-34        16519
35-44        13240
18-24         9210
45-54         6275
55-64         2626
65 - over      942
Name: ResponseId, dtype: int64

In [235]:
df["Age"].isnull().sum()

np.int64(378)

In [236]:
df.groupby("EdLevel")["ResponseId"].count().sort_values(ascending=False)

EdLevel
Bachelor’s degree (B.A., B.S., B.Eng., etc.)                                          20278
Master’s degree (M.A., M.S., M.Eng., MBA, etc.)                                       12588
Some college/university study without earning a degree                                 6182
Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)     3631
Professional degree (JD, MD, Ph.D, Ed.D, etc.)                                         2624
Associate degree (A.A., A.S., etc.)                                                    1562
Other (please specify):                                                                 701
Primary/elementary school                                                               582
Name: ResponseId, dtype: int64

In [237]:
df["EdLevel"] = df["EdLevel"].str.replace(r"^Bachelor.*$", "Bachelor", regex=True)
df["EdLevel"] = df["EdLevel"].str.replace(r"^Master.*$", "Master", regex=True)
df["EdLevel"] = df["EdLevel"].str.replace(r"Secondary school.*$", "Secondary school", regex=True)
df["EdLevel"] = df["EdLevel"].str.replace(r"Some college.*$", "Some college/university", regex=True)
df["EdLevel"] = df["EdLevel"].str.replace(r"Professional.*$", "PhD", regex=True)
df["EdLevel"] = df["EdLevel"].str.replace(r"Associate.*$", "Associate", regex=True)
df["EdLevel"] = df["EdLevel"].str.replace(r"Other.*$", "Other", regex=True)

###### For Clarification purposes the column "EdLevel" implying "Education Level" has been totally replaced with some other definitions they are as follows:

###### 1. Bachelor’s degree (B.A., B.S., B.Eng., etc.) = Bachelor
###### 2. Master’s degree (M.A., M.S., M.Eng., MBA, etc.)  = Master
###### 3. Some college/university study without earning a degree = Some college/university
###### 4. Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.) = Secondary school
###### 5. Professional degree (JD, MD, Ph.D, Ed.D, etc.) = PhD
###### 6. Associate degree (A.A., A.S., etc.) = Associate
###### 7. Other (please specify) = Other
###### 8. Primary/elementary school = Primary/elemntary school

In [238]:
df.head()

,ResponseId,Age,EdLevel,Employment,WorkExp,YearsCode,DevType,OrgSize,ICorPM,RemoteWork,...,NewRole,ToolCountWork,ToolCountPersonal,Country,Currency,CompTotal,AISelect,AIAgents,ConvertedCompYearly,JobSat
0,1,25-34,Master,Employed,8.0,14.0,"Developer, mobile",20 to 99 employees,People manager,Remote,...,I have neither consider or transitioned into a...,7.0,3.0,Ukraine,EUR European Euro,52800.0,"Yes, I use AI tools monthly or infrequently","Yes, I use AI agents at work monthly or infreq...",61256.0,10.0
1,2,25-34,Associate,Employed,2.0,10.0,"Developer, back-end",500 to 999 employees,Individual contributor,"Hybrid (some in-person, leans heavy to flexibi...",...,I have transitioned into a new career and/or i...,6.0,5.0,Netherlands,EUR European Euro,90000.0,"Yes, I use AI tools weekly","No, and I don't plan to",104413.0,9.0
2,3,35-44,Bachelor,"Independent contractor, freelancer, or self-em...",10.0,12.0,"Developer, front-end",NaN,NaN,NaN,...,I have transitioned into a new career and/or i...,3.0,3.0,Ukraine,UAH Ukrainian hryvnia,2214000.0,"Yes, I use AI tools daily","Yes, I use AI agents at work weekly",53061.0,8.0
3,4,35-44,Bachelor,Employed,4.0,5.0,"Developer, back-end","10,000 or more employees",Individual contributor,Remote,...,I have neither consider or transitioned into a...,NaN,NaN,Ukraine,EUR European Euro,31200.0,"Yes, I use AI tools weekly","Yes, I use AI agents at work monthly or infreq...",36197.0,6.0
4,5,35-44,Master,"Independent contractor, freelancer, or self-em...",21.0,22.0,Engineering manager,NaN,NaN,NaN,...,I have neither consider or transitioned into a...,4.0,3.0,Ukraine,USD United States dollar,60000.0,"Yes, I use AI tools weekly","No, and I don't plan to",60000.0,7.0

In [239]:
df.groupby("Employment")["ResponseId"].count().sort_values(ascending=False)

Employment
Employed                                                33750
Independent contractor, freelancer, or self-employed     6708
Student                                                  4427
Not employed                                             2227
Retired                                                   708
I prefer not to say                                       518
Name: ResponseId, dtype: int64

###### For Clarification purposes the employment are replaced as follows:

###### 1. Independent contractor, freelancer, or self-employed = Contractor/Freelancer/Self-employed

In [ ]:
df["Employment"] = df["Employment"].str.replace(r"Independent.*$", "Contractor/Freelancer/Self-employed", regex=True)

,ResponseId,Age,EdLevel,Employment,WorkExp,YearsCode,DevType,OrgSize,ICorPM,RemoteWork,...,NewRole,ToolCountWork,ToolCountPersonal,Country,Currency,CompTotal,AISelect,AIAgents,ConvertedCompYearly,JobSat
0,1,25-34,Master,Employed,8.0,14.0,"Developer, mobile",20 to 99 employees,People manager,Remote,...,I have neither consider or transitioned into a...,7.0,3.0,Ukraine,EUR European Euro,52800.0,"Yes, I use AI tools monthly or infrequently","Yes, I use AI agents at work monthly or infreq...",61256.0,10.0
1,2,25-34,Associate,Employed,2.0,10.0,"Developer, back-end",500 to 999 employees,Individual contributor,"Hybrid (some in-person, leans heavy to flexibi...",...,I have transitioned into a new career and/or i...,6.0,5.0,Netherlands,EUR European Euro,90000.0,"Yes, I use AI tools weekly","No, and I don't plan to",104413.0,9.0
2,3,35-44,Bachelor,Contractor/Freelancer/Self-employed,10.0,12.0,"Developer, front-end",NaN,NaN,NaN,...,I have transitioned into a new career and/or i...,3.0,3.0,Ukraine,UAH Ukrainian hryvnia,2214000.0,"Yes, I use AI tools daily","Yes, I use AI agents at work weekly",53061.0,8.0
3,4,35-44,Bachelor,Employed,4.0,5.0,"Developer, back-end","10,000 or more employees",Individual contributor,Remote,...,I have neither consider or transitioned into a...,NaN,NaN,Ukraine,EUR European Euro,31200.0,"Yes, I use AI tools weekly","Yes, I use AI agents at work monthly or infreq...",36197.0,6.0
4,5,35-44,Master,Contractor/Freelancer/Self-employed,21.0,22.0,Engineering manager,NaN,NaN,NaN,...,I have neither consider or transitioned into a...,4.0,3.0,Ukraine,USD United States dollar,60000.0,"Yes, I use AI tools weekly","No, and I don't plan to",60000.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49185,49187,18-24,Bachelor,Employed,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49186,49188,45-54,Some college/university,Employed,25.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49187,49189,35-44,Master,Employed,17.0,31.0,"Architect, software or solutions","10,000 or more employees",People manager,"Hybrid (some in-person, leans heavy to flexibi...",...,I have somewhat considered changing my career ...,25.0,35.0,Italy,EUR European Euro,80000.0,"Yes, I use AI tools monthly or infrequently","No, I use AI exclusively in copilot/autocomple...",NaN,9.0
49188,49190,25-34,PhD,Contractor/Freelancer/Self-employed,2.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49189,49191,18-24,Some college/university,Student,NaN,6.0,Student,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN